const odds = [
  {
    updated: 1638834231531,
    created: 1638834231531,
    id: 972,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 3.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.47,
      decimalOdd: 1.7,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231532,
    created: 1638834231532,
    id: 973,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 4.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.448,
      decimalOdd: 1.79,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231532,
    created: 1638834231532,
    id: 974,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 5.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.427,
      decimalOdd: 1.88,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231531,
    created: 1638834231531,
    id: 961,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 2.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.46,
      decimalOdd: 1.74,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231531,
    created: 1638834231531,
    id: 962,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 3.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.437,
      decimalOdd: 1.83,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231531,
    created: 1638834231531,
    id: 963,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 4.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.416,
      decimalOdd: 1.92,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231531,
    created: 1638834231531,
    id: 964,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 5.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.395,
      decimalOdd: 2.02,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231531,
    created: 1638834231531,
    id: 965,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 6.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.375,
      decimalOdd: 2.13,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231531,
    created: 1638834231531,
    id: 966,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 7.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.355,
      decimalOdd: 2.25,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231531,
    created: 1638834231531,
    id: 967,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 8.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.337,
      decimalOdd: 2.38,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231531,
    created: 1638834231531,
    id: 968,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 9.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.318,
      decimalOdd: 2.51,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231531,
    created: 1638834231531,
    id: 969,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 10.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.301,
      decimalOdd: 2.66,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231531,
    created: 1638834231531,
    id: 970,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 11.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.284,
      decimalOdd: 2.82,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231531,
    created: 1638834231531,
    id: 971,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 2.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.492,
      decimalOdd: 1.63,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231532,
    created: 1638834231532,
    id: 975,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 6.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.406,
      decimalOdd: 1.97,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231532,
    created: 1638834231532,
    id: 976,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 7.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.386,
      decimalOdd: 2.07,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231532,
    created: 1638834231532,
    id: 977,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 8.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.366,
      decimalOdd: 2.18,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231532,
    created: 1638834231532,
    id: 978,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 9.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.347,
      decimalOdd: 2.3,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231532,
    created: 1638834231532,
    id: 979,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 10.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.329,
      decimalOdd: 2.43,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231532,
    created: 1638834231532,
    id: 980,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 11.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.311,
      decimalOdd: 2.57,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231532,
    created: 1638834231532,
    id: 981,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 2.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.522,
      decimalOdd: 1.53,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231532,
    created: 1638834231532,
    id: 982,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 3.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.5,
      decimalOdd: 1.6,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231532,
    created: 1638834231532,
    id: 983,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 4.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.478,
      decimalOdd: 1.67,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231532,
    created: 1638834231532,
    id: 984,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 5.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.456,
      decimalOdd: 1.75,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231532,
    created: 1638834231532,
    id: 985,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 6.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.435,
      decimalOdd: 1.84,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231532,
    created: 1638834231532,
    id: 986,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 7.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.415,
      decimalOdd: 1.93,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231532,
    created: 1638834231532,
    id: 987,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 8.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.395,
      decimalOdd: 2.03,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231532,
    created: 1638834231532,
    id: 988,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 9.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.375,
      decimalOdd: 2.13,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231532,
    created: 1638834231532,
    id: 989,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 10.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.356,
      decimalOdd: 2.25,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231532,
    created: 1638834231532,
    id: 990,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 11.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.337,
      decimalOdd: 2.37,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231532,
    created: 1638834231532,
    id: 991,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 2.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.542,
      decimalOdd: 1.48,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231532,
    created: 1638834231532,
    id: 992,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 3.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.52,
      decimalOdd: 1.54,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231532,
    created: 1638834231532,
    id: 993,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 4.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.498,
      decimalOdd: 1.61,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231532,
    created: 1638834231532,
    id: 994,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 5.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.476,
      decimalOdd: 1.68,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231533,
    created: 1638834231533,
    id: 995,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 6.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.455,
      decimalOdd: 1.76,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231533,
    created: 1638834231533,
    id: 996,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 7.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.434,
      decimalOdd: 1.84,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231533,
    created: 1638834231533,
    id: 997,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 8.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.414,
      decimalOdd: 1.93,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231533,
    created: 1638834231533,
    id: 998,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 9.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.394,
      decimalOdd: 2.03,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231533,
    created: 1638834231533,
    id: 999,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 10.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.374,
      decimalOdd: 2.14,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231533,
    created: 1638834231533,
    id: 1000,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.kills",
        operator: "gt",
        value: 11.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.355,
      decimalOdd: 2.25,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231533,
    created: 1638834231533,
    id: 1001,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_10",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 2.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.387,
      decimalOdd: 2.07,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231533,
    created: 1638834231533,
    id: 1002,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_10",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 3.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.367,
      decimalOdd: 2.18,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231533,
    created: 1638834231533,
    id: 1003,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_10",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 4.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.348,
      decimalOdd: 2.3,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231533,
    created: 1638834231533,
    id: 1004,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_10",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 5.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.33,
      decimalOdd: 2.42,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231533,
    created: 1638834231533,
    id: 1005,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_10",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 6.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.313,
      decimalOdd: 2.56,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231533,
    created: 1638834231533,
    id: 1006,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_10",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 7.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.296,
      decimalOdd: 2.7,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231533,
    created: 1638834231533,
    id: 1007,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_10",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 8.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.28,
      decimalOdd: 2.85,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231533,
    created: 1638834231533,
    id: 1008,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_10",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 9.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.265,
      decimalOdd: 3.02,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231533,
    created: 1638834231533,
    id: 1009,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_10",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 10.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.25,
      decimalOdd: 3.19,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231533,
    created: 1638834231533,
    id: 1010,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_10",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 11.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.236,
      decimalOdd: 3.38,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231534,
    created: 1638834231534,
    id: 1011,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_5",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 2.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.419,
      decimalOdd: 1.91,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231535,
    created: 1638834231535,
    id: 1012,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_5",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 3.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.398,
      decimalOdd: 2.01,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231535,
    created: 1638834231535,
    id: 1013,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_5",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 4.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.378,
      decimalOdd: 2.11,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231535,
    created: 1638834231535,
    id: 1014,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_5",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 5.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.36,
      decimalOdd: 2.23,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231535,
    created: 1638834231535,
    id: 1015,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_5",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 6.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.341,
      decimalOdd: 2.34,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231535,
    created: 1638834231535,
    id: 1016,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_5",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 7.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.324,
      decimalOdd: 2.47,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231535,
    created: 1638834231535,
    id: 1017,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_5",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 8.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.307,
      decimalOdd: 2.6,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231535,
    created: 1638834231535,
    id: 1018,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_5",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 9.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.291,
      decimalOdd: 2.75,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231535,
    created: 1638834231535,
    id: 1019,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_5",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 10.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.276,
      decimalOdd: 2.9,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231535,
    created: 1638834231535,
    id: 1020,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_5",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 11.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.261,
      decimalOdd: 3.07,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231535,
    created: 1638834231535,
    id: 1021,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_5",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 2.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.448,
      decimalOdd: 1.79,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231535,
    created: 1638834231535,
    id: 1022,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_5",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 3.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.427,
      decimalOdd: 1.87,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231535,
    created: 1638834231535,
    id: 1023,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_5",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 4.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.407,
      decimalOdd: 1.97,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231535,
    created: 1638834231535,
    id: 1024,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_5",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 5.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.388,
      decimalOdd: 2.06,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231536,
    created: 1638834231536,
    id: 1025,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_5",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 6.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.369,
      decimalOdd: 2.17,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231536,
    created: 1638834231536,
    id: 1026,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_5",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 7.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.351,
      decimalOdd: 2.28,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231536,
    created: 1638834231536,
    id: 1027,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_5",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 8.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.333,
      decimalOdd: 2.4,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231536,
    created: 1638834231536,
    id: 1028,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_5",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 9.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.316,
      decimalOdd: 2.53,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231536,
    created: 1638834231536,
    id: 1029,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_5",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 10.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.3,
      decimalOdd: 2.67,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231536,
    created: 1638834231536,
    id: 1030,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_5",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 11.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.284,
      decimalOdd: 2.81,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231536,
    created: 1638834231536,
    id: 1031,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_3",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 2.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.468,
      decimalOdd: 1.71,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231536,
    created: 1638834231536,
    id: 1032,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_3",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 3.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.447,
      decimalOdd: 1.79,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231536,
    created: 1638834231536,
    id: 1033,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_3",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 4.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.426,
      decimalOdd: 1.88,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231536,
    created: 1638834231536,
    id: 1034,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_3",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 5.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.407,
      decimalOdd: 1.97,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231536,
    created: 1638834231536,
    id: 1035,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_3",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 6.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.388,
      decimalOdd: 2.06,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231536,
    created: 1638834231536,
    id: 1036,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_3",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 7.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.369,
      decimalOdd: 2.17,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231536,
    created: 1638834231536,
    id: 1037,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_3",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 8.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.351,
      decimalOdd: 2.28,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231536,
    created: 1638834231536,
    id: 1038,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_3",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 9.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.334,
      decimalOdd: 2.39,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231536,
    created: 1638834231536,
    id: 1039,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_3",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 10.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.317,
      decimalOdd: 2.52,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231536,
    created: 1638834231536,
    id: 1040,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.top_3",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 11.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.301,
      decimalOdd: 2.66,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231536,
    created: 1638834231536,
    id: 1041,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 2.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.269,
      decimalOdd: 2.97,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231536,
    created: 1638834231536,
    id: 1042,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 3.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.251,
      decimalOdd: 3.19,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231536,
    created: 1638834231536,
    id: 1043,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 4.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.234,
      decimalOdd: 3.42,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231537,
    created: 1638834231537,
    id: 1044,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 5.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.218,
      decimalOdd: 3.67,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231537,
    created: 1638834231537,
    id: 1045,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 6.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.203,
      decimalOdd: 3.95,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231537,
    created: 1638834231537,
    id: 1046,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 7.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.189,
      decimalOdd: 4.24,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231537,
    created: 1638834231537,
    id: 1047,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 8.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.175,
      decimalOdd: 4.57,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231537,
    created: 1638834231537,
    id: 1048,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 9.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.163,
      decimalOdd: 4.92,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231537,
    created: 1638834231537,
    id: 1049,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 10.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.151,
      decimalOdd: 5.3,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231537,
    created: 1638834231537,
    id: 1050,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 11.5,
      },
    ],
    mode: "BR_SOLO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.14,
      decimalOdd: 5.72,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231537,
    created: 1638834231537,
    id: 1051,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 2.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.296,
      decimalOdd: 2.71,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231537,
    created: 1638834231537,
    id: 1052,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 3.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.276,
      decimalOdd: 2.89,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231537,
    created: 1638834231537,
    id: 1053,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 4.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.258,
      decimalOdd: 3.1,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231537,
    created: 1638834231537,
    id: 1054,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 5.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.241,
      decimalOdd: 3.32,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231537,
    created: 1638834231537,
    id: 1055,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 6.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.225,
      decimalOdd: 3.56,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231537,
    created: 1638834231537,
    id: 1056,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 7.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.209,
      decimalOdd: 3.82,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231537,
    created: 1638834231537,
    id: 1057,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 8.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.195,
      decimalOdd: 4.11,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231537,
    created: 1638834231537,
    id: 1058,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 9.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.181,
      decimalOdd: 4.42,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231537,
    created: 1638834231537,
    id: 1059,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 10.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.168,
      decimalOdd: 4.75,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231537,
    created: 1638834231537,
    id: 1060,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 11.5,
      },
    ],
    mode: "BR_DUO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.156,
      decimalOdd: 5.12,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231537,
    created: 1638834231537,
    id: 1061,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 2.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.321,
      decimalOdd: 2.49,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231538,
    created: 1638834231538,
    id: 1062,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 3.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.301,
      decimalOdd: 2.66,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231538,
    created: 1638834231538,
    id: 1063,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 4.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.282,
      decimalOdd: 2.84,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231538,
    created: 1638834231538,
    id: 1064,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 5.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.263,
      decimalOdd: 3.04,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231538,
    created: 1638834231538,
    id: 1065,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 6.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.246,
      decimalOdd: 3.25,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231538,
    created: 1638834231538,
    id: 1066,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 7.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.23,
      decimalOdd: 3.48,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231538,
    created: 1638834231538,
    id: 1067,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 8.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.214,
      decimalOdd: 3.73,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231538,
    created: 1638834231538,
    id: 1068,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 9.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.2,
      decimalOdd: 4.01,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231538,
    created: 1638834231538,
    id: 1069,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 10.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.186,
      decimalOdd: 4.31,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231538,
    created: 1638834231538,
    id: 1070,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 11.5,
      },
    ],
    mode: "BR_TRIO",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.173,
      decimalOdd: 4.63,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231538,
    created: 1638834231538,
    id: 1071,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 2.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.339,
      decimalOdd: 2.36,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231538,
    created: 1638834231538,
    id: 1072,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 3.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.318,
      decimalOdd: 2.51,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231538,
    created: 1638834231538,
    id: 1073,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 4.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.298,
      decimalOdd: 2.68,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231538,
    created: 1638834231538,
    id: 1074,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 5.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.279,
      decimalOdd: 2.86,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231538,
    created: 1638834231538,
    id: 1075,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 6.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.261,
      decimalOdd: 3.06,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231538,
    created: 1638834231538,
    id: 1076,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 7.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.244,
      decimalOdd: 3.28,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231538,
    created: 1638834231538,
    id: 1077,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 8.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.228,
      decimalOdd: 3.51,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231538,
    created: 1638834231538,
    id: 1078,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 9.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.213,
      decimalOdd: 3.76,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231538,
    created: 1638834231538,
    id: 1079,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 10.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.198,
      decimalOdd: 4.04,
    },
    matchId: null,
    won: null,
  },
  {
    updated: 1638834231539,
    created: 1638834231539,
    id: 1080,
    tradingStatus: "OPEN",
    conditions: [
      {
        attribute: "player.win",
        operator: "eq",
        value: true,
      },
      {
        attribute: "player.kills",
        operator: "gt",
        value: 11.5,
      },
    ],
    mode: "BR_SQUAD",
    platform: "KBM",
    title: "fortnite",
    price: {
      overround: 0.125,
      probability: 0.185,
      decimalOdd: 4.34,
    },
    matchId: null,
    won: null,
  },
];
export default odds;
